language: cpp

compiler: 
    - g++

before_install:
    - sudo apt-get update -qq
    - sudo apt-get upgrade -y
    - sudo apt-get install bison flex

script:
    - make 

notifications:
    email:
        - parth.kolekar@students.iiit.ac.in
